site_name: DataGuides
site_author: Banj
site_url: http://www.DataGuid.es
repo_url: https://github.com/banj/DataGuides
repo_name: DataGuides
pages:
- [index.md, Home]
- [about.md, About]
- [check.md, Checklist for Educators]
- [explain.md, Best Practices for Data-focused Educators]
- [tools.md, Tools for Data-focused Educators]
theme: readthedocs
